MLIR: include/mlir-c/AffineMap.h File Reference
AffineMap.h File Reference
#include "mlir-c/IR.h"
Functions
DEFINE_C_API_STRUCT (MlirAffineMap, const void)
MlirContext mlirAffineMapGetContext (MlirAffineMap affineMap)
Gets the context that the given affine map was created with.
int mlirAffineMapIsNull (MlirAffineMap affineMap)
Checks whether an affine map is null.
int mlirAffineMapEqual (MlirAffineMap a1, MlirAffineMap a2)
Checks if two affine maps are equal.
void mlirAffineMapPrint (MlirAffineMap affineMap, MlirStringCallback callback, void *userData)
Prints an affine map by sending chunks of the string representation and forwarding userData tocallback`.
void mlirAffineMapDump (MlirAffineMap affineMap)
Prints the affine map to the standard error stream.
MlirAffineMap mlirAffineMapEmptyGet (MlirContext ctx)
Creates a zero result affine map with no dimensions or symbols in the context.
MlirAffineMap mlirAffineMapGet (MlirContext ctx, intptr_t dimCount, intptr_t symbolCount)
Creates a zero result affine map of the given dimensions and symbols in the context.
MlirAffineMap mlirAffineMapConstantGet (MlirContext ctx, int64_t val)
Creates a single constant result affine map in the context.
MlirAffineMap mlirAffineMapMultiDimIdentityGet (MlirContext ctx, intptr_t numDims)
Creates an affine map with 'numDims' identity in the context.
MlirAffineMap mlirAffineMapMinorIdentityGet (MlirContext ctx, intptr_t dims, intptr_t results)
Creates an identity affine map on the most minor dimensions in the context.
MlirAffineMap mlirAffineMapPermutationGet (MlirContext ctx, intptr_t size, unsigned *permutation)
Creates an affine map with a permutation expression and its size in the context.
int mlirAffineMapIsIdentity (MlirAffineMap affineMap)
Checks whether the given affine map is an identity affine map.
int mlirAffineMapIsMinorIdentity (MlirAffineMap affineMap)
Checks whether the given affine map is a minor identity affine map.
int mlirAffineMapIsEmpty (MlirAffineMap affineMap)
Checks whether the given affine map is an empty affine map.
int mlirAffineMapIsSingleConstant (MlirAffineMap affineMap)
Checks whether the given affine map is a single result constant affine map.
int64_t mlirAffineMapGetSingleConstantResult (MlirAffineMap affineMap)
Returns the constant result of the given affine map.
intptr_t mlirAffineMapGetNumDims (MlirAffineMap affineMap)
Returns the number of dimensions of the given affine map.
intptr_t mlirAffineMapGetNumSymbols (MlirAffineMap affineMap)
Returns the number of symbols of the given affine map.
intptr_t mlirAffineMapGetNumResults (MlirAffineMap affineMap)
Returns the number of results of the given affine map.
intptr_t mlirAffineMapGetNumInputs (MlirAffineMap affineMap)
Returns the number of inputs (dimensions + symbols) of the given affine map.
int mlirAffineMapIsProjectedPermutation (MlirAffineMap affineMap)
Checks whether the given affine map represents a subset of a symbol-less permutation map.
int mlirAffineMapIsPermutation (MlirAffineMap affineMap)
Checks whether the given affine map represents a symbol-less permutation map.
MlirAffineMap mlirAffineMapGetSubMap (MlirAffineMap affineMap, intptr_t size, intptr_t *resultPos)
Returns the affine map consisting of the resultPos subset.
MlirAffineMap mlirAffineMapGetMajorSubMap (MlirAffineMap affineMap, intptr_t numResults)
Returns the affine map consisting of the most major numResults results.
MlirAffineMap mlirAffineMapGetMinorSubMap (MlirAffineMap affineMap, intptr_t numResults)
Returns the affine map consisting of the most minor numResults results.
Function Documentation
DEFINE_C_API_STRUCT()
DEFINE_C_API_STRUCT (MlirAffineMap , const void)
mlirAffineMapConstantGet()
MlirAffineMap mlirAffineMapConstantGet (MlirContext ctx, int64_t val)
Creates a single constant result affine map in the context.
The affine map is owned by the context.
Definition at line 46 of file AffineMap.cpp.
References mlir::AffineMap::getConstantMap(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapDump()
void mlirAffineMapDump (MlirAffineMap affineMap)
Prints the affine map to the standard error stream.
Definition at line 35 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapEmptyGet()
MlirAffineMap mlirAffineMapEmptyGet (MlirContext ctx)
Creates a zero result affine map with no dimensions or symbols in the context.
The affine map is owned by the context.
Definition at line 37 of file AffineMap.cpp.
References mlir::AffineMap::get(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapEqual()
int mlirAffineMapEqual (MlirAffineMap a1, MlirAffineMap a2)
Checks if two affine maps are equal.
Definition at line 24 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGet()
MlirAffineMap mlirAffineMapGet (MlirContext ctx, intptr_t dimCount, intptr_t symbolCount)
Creates a zero result affine map of the given dimensions and symbols in the context.
The affine map is owned by the context.
Definition at line 41 of file AffineMap.cpp.
References mlir::AffineMap::get(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetContext()
MlirContext mlirAffineMapGetContext (MlirAffineMap affineMap)
Gets the context that the given affine map was created with.
Definition at line 20 of file AffineMap.cpp.
References unwrap(), and wrap().
mlirAffineMapGetMajorSubMap()
MlirAffineMap mlirAffineMapGetMajorSubMap (MlirAffineMap affineMap, intptr_t numResults)
Returns the affine map consisting of the most major numResults results.
Returns the null AffineMap if the numResults is equal to zero. Returns the affineMap if numResults is greater or equals to number of results of the given affine map.
Definition at line 119 of file AffineMap.cpp.
References unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetMinorSubMap()
MlirAffineMap mlirAffineMapGetMinorSubMap (MlirAffineMap affineMap, intptr_t numResults)
Returns the affine map consisting of the most minor numResults results.
Returns the null AffineMap if the numResults is equal to zero. Returns the affineMap if numResults is greater or equals to number of results of the given affine map.
Definition at line 124 of file AffineMap.cpp.
References unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetNumDims()
intptr_t mlirAffineMapGetNumDims (MlirAffineMap affineMap)
Returns the number of dimensions of the given affine map.
Definition at line 86 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetNumInputs()
intptr_t mlirAffineMapGetNumInputs (MlirAffineMap affineMap)
Returns the number of inputs (dimensions + symbols) of the given affine map.
Definition at line 98 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetNumResults()
intptr_t mlirAffineMapGetNumResults (MlirAffineMap affineMap)
Returns the number of results of the given affine map.
Definition at line 94 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetNumSymbols()
intptr_t mlirAffineMapGetNumSymbols (MlirAffineMap affineMap)
Returns the number of symbols of the given affine map.
Definition at line 90 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetSingleConstantResult()
int64_t mlirAffineMapGetSingleConstantResult (MlirAffineMap affineMap)
Returns the constant result of the given affine map.
The function asserts that the map has a single constant result.
Definition at line 82 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetSubMap()
MlirAffineMap mlirAffineMapGetSubMap (MlirAffineMap affineMap, intptr_t size, intptr_t * resultPos)
Returns the affine map consisting of the resultPos subset.
Definition at line 110 of file AffineMap.cpp.
References unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsEmpty()
int mlirAffineMapIsEmpty (MlirAffineMap affineMap)
Checks whether the given affine map is an empty affine map.
Definition at line 74 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsIdentity()
int mlirAffineMapIsIdentity (MlirAffineMap affineMap)
Checks whether the given affine map is an identity affine map.
The function asserts that the number of dimensions is greater or equal to the number of results.
Definition at line 66 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsMinorIdentity()
int mlirAffineMapIsMinorIdentity (MlirAffineMap affineMap)
Checks whether the given affine map is a minor identity affine map.
Definition at line 70 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsNull()
int mlirAffineMapIsNull (MlirAffineMap affineMap) inline
Checks whether an affine map is null.
Definition at line 25 of file AffineMap.h.
References mlirAffineMapConstantGet(), mlirAffineMapDump(), mlirAffineMapEmptyGet(), mlirAffineMapEqual(), mlirAffineMapGet(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetNumDims(), mlirAffineMapGetNumInputs(), mlirAffineMapGetNumResults(), mlirAffineMapGetNumSymbols(), mlirAffineMapGetSingleConstantResult(), mlirAffineMapGetSubMap(), mlirAffineMapIsEmpty(), mlirAffineMapIsIdentity(), mlirAffineMapIsMinorIdentity(), mlirAffineMapIsPermutation(), mlirAffineMapIsProjectedPermutation(), mlirAffineMapIsSingleConstant(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), and mlirAffineMapPrint().
mlirAffineMapIsPermutation()
int mlirAffineMapIsPermutation (MlirAffineMap affineMap)
Checks whether the given affine map represents a symbol-less permutation map.
Definition at line 106 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsProjectedPermutation()
int mlirAffineMapIsProjectedPermutation (MlirAffineMap affineMap)
Checks whether the given affine map represents a subset of a symbol-less permutation map.
Definition at line 102 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsSingleConstant()
int mlirAffineMapIsSingleConstant (MlirAffineMap affineMap)
Checks whether the given affine map is a single result constant affine map.
Definition at line 78 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapMinorIdentityGet()
MlirAffineMap mlirAffineMapMinorIdentityGet (MlirContext ctx, intptr_t dims, intptr_t results)
Creates an identity affine map on the most minor dimensions in the context.
The affine map is owned by the context. The function asserts that the number of dimensions is greater or equal to the number of results.
Definition at line 55 of file AffineMap.cpp.
References mlir::AffineMap::getMinorIdentityMap(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapMultiDimIdentityGet()
MlirAffineMap mlirAffineMapMultiDimIdentityGet (MlirContext ctx, intptr_t numDims)
Creates an affine map with 'numDims' identity in the context.
The affine map is owned by the context.
Definition at line 50 of file AffineMap.cpp.
References mlir::AffineMap::getMultiDimIdentityMap(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapPermutationGet()
MlirAffineMap mlirAffineMapPermutationGet (MlirContext ctx, intptr_t size, unsigned * permutation)
Creates an affine map with a permutation expression and its size in the context.
The permutation expression is a non-empty vector of integers. The elements of the permutation vector must be continuous from 0 and cannot be repeated (i.e. [1,2,0] is a valid permutation. [2,0] or [1,1,2] is an invalid invalid permutation.) The affine map is owned by the context.
Definition at line 60 of file AffineMap.cpp.
References mlir::AffineMap::getPermutationMap(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapPrint()
void mlirAffineMapPrint (MlirAffineMap affineMap, MlirStringCallback callback, void * userData)
Prints an affine map by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 28 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().