MLIR: include/mlir-c/IR.h File Reference
IR.h File Reference
#include <stdint.h>
#include "mlir-c/Support.h"
Classes
struct MlirNamedAttribute
Named MLIR attribute.
struct MlirOperationState
An auxiliary class for constructing operations.
Macros
#define DEFINE_C_API_STRUCT(name, storage)
Opaque type declarations.
Typedefs
typedef struct MlirNamedAttribute MlirNamedAttribute
typedef void(* MlirStringCallback) (const char *, intptr_t, void *)
A callback for returning string references.
typedef struct MlirOperationState MlirOperationState
Functions
DEFINE_C_API_STRUCT (MlirContext, void)
DEFINE_C_API_STRUCT (MlirDialect, void)
DEFINE_C_API_STRUCT (MlirOperation, void)
DEFINE_C_API_STRUCT (MlirBlock, void)
DEFINE_C_API_STRUCT (MlirRegion, void)
DEFINE_C_API_STRUCT (MlirValue, const void)
DEFINE_C_API_STRUCT (MlirAttribute, const void)
DEFINE_C_API_STRUCT (MlirType, const void)
DEFINE_C_API_STRUCT (MlirLocation, const void)
DEFINE_C_API_STRUCT (MlirModule, const void)
MlirContext mlirContextCreate ()
Creates an MLIR context and transfers its ownership to the caller.
int mlirContextEqual (MlirContext ctx1, MlirContext ctx2)
Checks if two contexts are equal.
int mlirContextIsNull (MlirContext context)
Checks whether a context is null.
void mlirContextDestroy (MlirContext context)
Takes an MLIR context owned by the caller and destroys it.
void mlirContextSetAllowUnregisteredDialects (MlirContext context, int allow)
Sets whether unregistered dialects are allowed in this context.
int mlirContextGetAllowUnregisteredDialects (MlirContext context)
Returns whether the context allows unregistered dialects.
intptr_t mlirContextGetNumRegisteredDialects (MlirContext context)
Returns the number of dialects registered with the given context.
intptr_t mlirContextGetNumLoadedDialects (MlirContext context)
Returns the number of dialects loaded by the context.
MlirDialect mlirContextGetOrLoadDialect (MlirContext context, MlirStringRef name)
Gets the dialect instance owned by the given context using the dialect namespace to identify it, loads (i.e., constructs the instance of) the dialect if necessary.
MlirContext mlirDialectGetContext (MlirDialect dialect)
Returns the context that owns the dialect.
int mlirDialectIsNull (MlirDialect dialect)
Checks if the dialect is null.
int mlirDialectEqual (MlirDialect dialect1, MlirDialect dialect2)
Checks if two dialects that belong to the same context are equal.
MlirStringRef mlirDialectGetNamespace (MlirDialect dialect)
Returns the namespace of the given dialect.
MlirLocation mlirLocationFileLineColGet (MlirContext context, const char *filename, unsigned line, unsigned col)
Creates an File/Line/Column location owned by the given context.
MlirLocation mlirLocationUnknownGet (MlirContext context)
Creates a location with unknown position owned by the given context.
MlirContext mlirLocationGetContext (MlirLocation location)
Gets the context that a location was created with.
void mlirLocationPrint (MlirLocation location, MlirStringCallback callback, void *userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
MlirModule mlirModuleCreateEmpty (MlirLocation location)
Creates a new, empty module and transfers ownership to the caller.
MlirModule mlirModuleCreateParse (MlirContext context, const char *module)
Parses a module from the string and transfers ownership to the caller.
MlirContext mlirModuleGetContext (MlirModule module)
Gets the context that a module was created with.
int mlirModuleIsNull (MlirModule module)
Checks whether a module is null.
void mlirModuleDestroy (MlirModule module)
Takes a module owned by the caller and deletes it.
MlirOperation mlirModuleGetOperation (MlirModule module)
Views the module as a generic operation.
MlirOperationState mlirOperationStateGet (const char *name, MlirLocation loc)
Constructs an operation state from a name and a location.
void mlirOperationStateAddResults (MlirOperationState *state, intptr_t n, MlirType *results)
Adds a list of components to the operation state.
void mlirOperationStateAddOperands (MlirOperationState *state, intptr_t n, MlirValue *operands)
void mlirOperationStateAddOwnedRegions (MlirOperationState *state, intptr_t n, MlirRegion *regions)
void mlirOperationStateAddSuccessors (MlirOperationState *state, intptr_t n, MlirBlock *successors)
void mlirOperationStateAddAttributes (MlirOperationState *state, intptr_t n, MlirNamedAttribute *attributes)
MlirOperation mlirOperationCreate (const MlirOperationState *state)
Creates an operation and transfers ownership to the caller.
void mlirOperationDestroy (MlirOperation op)
Takes an operation owned by the caller and destroys it.
int mlirOperationIsNull (MlirOperation op)
Checks whether the underlying operation is null.
intptr_t mlirOperationGetNumRegions (MlirOperation op)
Returns the number of regions attached to the given operation.
MlirRegion mlirOperationGetRegion (MlirOperation op, intptr_t pos)
Returns pos-th region attached to the operation.
MlirOperation mlirOperationGetNextInBlock (MlirOperation op)
Returns an operation immediately following the given operation it its enclosing block.
intptr_t mlirOperationGetNumOperands (MlirOperation op)
Returns the number of operands of the operation.
MlirValue mlirOperationGetOperand (MlirOperation op, intptr_t pos)
Returns pos-th operand of the operation.
intptr_t mlirOperationGetNumResults (MlirOperation op)
Returns the number of results of the operation.
MlirValue mlirOperationGetResult (MlirOperation op, intptr_t pos)
Returns pos-th result of the operation.
intptr_t mlirOperationGetNumSuccessors (MlirOperation op)
Returns the number of successor blocks of the operation.
MlirBlock mlirOperationGetSuccessor (MlirOperation op, intptr_t pos)
Returns pos-th successor of the operation.
intptr_t mlirOperationGetNumAttributes (MlirOperation op)
Returns the number of attributes attached to the operation.
MlirNamedAttribute mlirOperationGetAttribute (MlirOperation op, intptr_t pos)
Return pos-th attribute of the operation.
MlirAttribute mlirOperationGetAttributeByName (MlirOperation op, const char *name)
Returns an attribute attached to the operation given its name.
void mlirOperationPrint (MlirOperation op, MlirStringCallback callback, void *userData)
Prints an operation by sending chunks of the string representation and forwarding userData tocallback`.
void mlirOperationDump (MlirOperation op)
Prints an operation to stderr.
MlirRegion mlirRegionCreate ()
Creates a new empty region and transfers ownership to the caller.
void mlirRegionDestroy (MlirRegion region)
Takes a region owned by the caller and destroys it.
int mlirRegionIsNull (MlirRegion region)
Checks whether a region is null.
MlirBlock mlirRegionGetFirstBlock (MlirRegion region)
Gets the first block in the region.
void mlirRegionAppendOwnedBlock (MlirRegion region, MlirBlock block)
Takes a block owned by the caller and appends it to the given region.
void mlirRegionInsertOwnedBlock (MlirRegion region, intptr_t pos, MlirBlock block)
Takes a block owned by the caller and inserts it at pos to the given region.
void mlirRegionInsertOwnedBlockAfter (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it after the (non-owned) reference block in the given region.
void mlirRegionInsertOwnedBlockBefore (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it before the (non-owned) reference block in the given region.
MlirBlock mlirBlockCreate (intptr_t nArgs, MlirType *args)
Creates a new empty block with the given argument types and transfers ownership to the caller.
void mlirBlockDestroy (MlirBlock block)
Takes a block owned by the caller and destroys it.
int mlirBlockIsNull (MlirBlock block)
Checks whether a block is null.
MlirBlock mlirBlockGetNextInRegion (MlirBlock block)
Returns the block immediately following the given block in its parent region.
MlirOperation mlirBlockGetFirstOperation (MlirBlock block)
Returns the first operation in the block.
void mlirBlockAppendOwnedOperation (MlirBlock block, MlirOperation operation)
Takes an operation owned by the caller and appends it to the block.
void mlirBlockInsertOwnedOperation (MlirBlock block, intptr_t pos, MlirOperation operation)
Takes an operation owned by the caller and inserts it as pos to the block.
void mlirBlockInsertOwnedOperationAfter (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it after the (non-owned) reference operation in the given block.
void mlirBlockInsertOwnedOperationBefore (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it before the (non-owned) reference operation in the given block.
intptr_t mlirBlockGetNumArguments (MlirBlock block)
Returns the number of arguments of the block.
MlirValue mlirBlockGetArgument (MlirBlock block, intptr_t pos)
Returns pos-th argument of the block.
void mlirBlockPrint (MlirBlock block, MlirStringCallback callback, void *userData)
Prints a block by sending chunks of the string representation and forwarding userData tocallback`.
MlirType mlirValueGetType (MlirValue value)
Returns the type of the value.
void mlirValuePrint (MlirValue value, MlirStringCallback callback, void *userData)
Prints a value by sending chunks of the string representation and forwarding userData tocallback`.
MlirType mlirTypeParseGet (MlirContext context, const char *type)
Parses a type.
MlirContext mlirTypeGetContext (MlirType type)
Gets the context that a type was created with.
int mlirTypeIsNull (MlirType type)
Checks whether a type is null.
int mlirTypeEqual (MlirType t1, MlirType t2)
Checks if two types are equal.
void mlirTypePrint (MlirType type, MlirStringCallback callback, void *userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
void mlirTypeDump (MlirType type)
Prints the type to the standard error stream.
MlirAttribute mlirAttributeParseGet (MlirContext context, const char *attr)
Parses an attribute.
MlirContext mlirAttributeGetContext (MlirAttribute attribute)
Gets the context that an attribute was created with.
int mlirAttributeIsNull (MlirAttribute attr)
Checks whether an attribute is null.
int mlirAttributeEqual (MlirAttribute a1, MlirAttribute a2)
Checks if two attributes are equal.
void mlirAttributePrint (MlirAttribute attr, MlirStringCallback callback, void *userData)
Prints an attribute by sending chunks of the string representation and forwarding userData tocallback`.
void mlirAttributeDump (MlirAttribute attr)
Prints the attribute to the standard error stream.
MlirNamedAttribute mlirNamedAttributeGet (const char *name, MlirAttribute attr)
Associates an attribute with the name.
Macro Definition Documentation
DEFINE_C_API_STRUCT
#define DEFINE_C_API_STRUCT (name, storage)
Value:
struct name {                                                                \
    storage *ptr;                                                              \
  };                                                                           \
  typedef struct name name
Opaque type declarations.
Types are exposed to C bindings as structs containing opaque pointers. They are not supposed to be inspected from C. This allows the underlying representation to change without affecting the API users. The use of structs instead of typedefs enables some type safety as structs are not implicitly convertible to each other.
Instances of these types may or may not own the underlying object (most often only point to an IR fragment without owning it). The ownership semantics is defined by how an instance of the type was obtained.
Definition at line 44 of file IR.h.
Typedef Documentation
MlirNamedAttribute
typedef struct MlirNamedAttribute MlirNamedAttribute
Definition at line 71 of file IR.h.
MlirOperationState
typedef struct MlirOperationState MlirOperationState
Definition at line 210 of file IR.h.
MlirStringCallback
typedef void(* MlirStringCallback) (const char *, intptr_t, void *)
A callback for returning string references.
This function is called back by the functions that need to return a reference to the portion of the string with the following arguments:
a pointer to the beginning of a string;
the length of the string (the pointer may point to a larger buffer, not necessarily null-terminated);
a pointer to user data forwarded from the printing call.
Definition at line 82 of file IR.h.
Function Documentation
DEFINE_C_API_STRUCT() [1/10]
DEFINE_C_API_STRUCT (MlirContext , void)
DEFINE_C_API_STRUCT() [2/10]
DEFINE_C_API_STRUCT (MlirDialect , void)
DEFINE_C_API_STRUCT() [3/10]
DEFINE_C_API_STRUCT (MlirOperation , void)
DEFINE_C_API_STRUCT() [4/10]
DEFINE_C_API_STRUCT (MlirBlock , void)
DEFINE_C_API_STRUCT() [5/10]
DEFINE_C_API_STRUCT (MlirRegion , void)
DEFINE_C_API_STRUCT() [6/10]
DEFINE_C_API_STRUCT (MlirValue , const void)
DEFINE_C_API_STRUCT() [7/10]
DEFINE_C_API_STRUCT (MlirAttribute , const void)
DEFINE_C_API_STRUCT() [8/10]
DEFINE_C_API_STRUCT (MlirType , const void)
DEFINE_C_API_STRUCT() [9/10]
DEFINE_C_API_STRUCT (MlirLocation , const void)
DEFINE_C_API_STRUCT() [10/10]
DEFINE_C_API_STRUCT (MlirModule , const void)
mlirAttributeDump()
void mlirAttributeDump (MlirAttribute attr)
Prints the attribute to the standard error stream.
Definition at line 471 of file IR.cpp.
References unwrap().
Referenced by mlirAttributeIsNull(), and mlir::python::PyType::operator==().
mlirAttributeEqual()
int mlirAttributeEqual (MlirAttribute a1, MlirAttribute a2)
Checks if two attributes are equal.
Definition at line 460 of file IR.cpp.
References unwrap().
Referenced by mlirAttributeIsNull(), and mlir::python::PyAttribute::operator==().
mlirAttributeGetContext()
MlirContext mlirAttributeGetContext (MlirAttribute attribute)
Gets the context that an attribute was created with.
Definition at line 456 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirAttributeIsNull()
int mlirAttributeIsNull (MlirAttribute attr) inline
Checks whether an attribute is null.
Definition at line 428 of file IR.h.
References mlirAttributeDump(), mlirAttributeEqual(), mlirAttributePrint(), and mlirNamedAttributeGet().
Referenced by mlir::python::PyType::operator==().
mlirAttributeParseGet()
MlirAttribute mlirAttributeParseGet (MlirContext context, const char * attr)
Parses an attribute.
The attribute is owned by the context.
Definition at line 452 of file IR.cpp.
References mlir::parseAttribute(), unwrap(), and wrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirAttributePrint()
void mlirAttributePrint (MlirAttribute attr, MlirStringCallback callback, void * userData)
Prints an attribute by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 464 of file IR.cpp.
References unwrap().
Referenced by mlirAttributeIsNull(), and mlir::python::PyType::operator==().
mlirBlockAppendOwnedOperation()
void mlirBlockAppendOwnedOperation (MlirBlock block, MlirOperation operation)
Takes an operation owned by the caller and appends it to the block.
Definition at line 355 of file IR.cpp.
References unwrap().
Referenced by mlirBlockInsertOwnedOperationBefore().
mlirBlockCreate()
MlirBlock mlirBlockCreate (intptr_t nArgs, MlirType * args)
Creates a new empty block with the given argument types and transfers ownership to the caller.
Definition at line 337 of file IR.cpp.
References mlir::Block::addArgument(), unwrap(), and wrap().
mlirBlockDestroy()
void mlirBlockDestroy (MlirBlock block)
Takes a block owned by the caller and destroys it.
Definition at line 392 of file IR.cpp.
References unwrap().
mlirBlockGetArgument()
MlirValue mlirBlockGetArgument (MlirBlock block, intptr_t pos)
Returns pos-th argument of the block.
Definition at line 400 of file IR.cpp.
References unwrap(), and wrap().
mlirBlockGetFirstOperation()
MlirOperation mlirBlockGetFirstOperation (MlirBlock block)
Returns the first operation in the block.
Definition at line 348 of file IR.cpp.
References mlir::Block::empty(), mlir::Block::front(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirBlockGetNextInRegion()
MlirBlock mlirBlockGetNextInRegion (MlirBlock block)
Returns the block immediately following the given block in its parent region.
Definition at line 344 of file IR.cpp.
References unwrap(), and wrap().
mlirBlockGetNumArguments()
intptr_t mlirBlockGetNumArguments (MlirBlock block)
Returns the number of arguments of the block.
Definition at line 396 of file IR.cpp.
References unwrap().
mlirBlockInsertOwnedOperation()
void mlirBlockInsertOwnedOperation (MlirBlock block, intptr_t pos, MlirOperation operation)
Takes an operation owned by the caller and inserts it as pos to the block.
This is an expensive operation that scans the block linearly, prefer insertBefore/After instead.
Definition at line 359 of file IR.cpp.
References unwrap().
mlirBlockInsertOwnedOperationAfter()
void mlirBlockInsertOwnedOperationAfter (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it after the (non-owned) reference operation in the given block.
If the reference is null, prepends the operation. Otherwise, the reference must belong to the block.
Definition at line 365 of file IR.cpp.
References mlir::Block::begin(), mlir::Block::getOperations(), mlirOperationIsNull(), and unwrap().
mlirBlockInsertOwnedOperationBefore()
void mlirBlockInsertOwnedOperationBefore (MlirBlock block, MlirOperation reference, MlirOperation operation)
Takes an operation owned by the caller and inserts it before the (non-owned) reference operation in the given block.
If the reference is null, appends the operation. Otherwise, the reference must belong to the block.
Definition at line 380 of file IR.cpp.
References mlirBlockAppendOwnedOperation(), mlirOperationIsNull(), and unwrap().
mlirBlockIsNull()
int mlirBlockIsNull (MlirBlock block)
Checks whether a block is null.
Definition at line 394 of file IR.cpp.
References unwrap().
Referenced by mlirRegionInsertOwnedBlockAfter(), mlirRegionInsertOwnedBlockBefore(), and mlir::python::PyBlock::PyBlock().
mlirBlockPrint()
void mlirBlockPrint (MlirBlock block, MlirStringCallback callback, void * userData)
Prints a block by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 404 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirContextCreate()
MlirContext mlirContextCreate ()
Creates an MLIR context and transfers its ownership to the caller.
Definition at line 28 of file IR.cpp.
References wrap().
Referenced by mlir::python::PyMlirContext::createNewContextForInit().
mlirContextDestroy()
void mlirContextDestroy (MlirContext context)
Takes an MLIR context owned by the caller and destroys it.
Definition at line 37 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PyMlirContext::~PyMlirContext().
mlirContextEqual()
int mlirContextEqual (MlirContext ctx1, MlirContext ctx2)
Checks if two contexts are equal.
Definition at line 33 of file IR.cpp.
References unwrap().
mlirContextGetAllowUnregisteredDialects()
int mlirContextGetAllowUnregisteredDialects (MlirContext context)
Returns whether the context allows unregistered dialects.
Definition at line 43 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PyType::operator==().
mlirContextGetNumLoadedDialects()
intptr_t mlirContextGetNumLoadedDialects (MlirContext context)
Returns the number of dialects loaded by the context.
Definition at line 52 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull().
mlirContextGetNumRegisteredDialects()
intptr_t mlirContextGetNumRegisteredDialects (MlirContext context)
Returns the number of dialects registered with the given context.
A registered dialect will be loaded if needed by the parser.
Definition at line 46 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull().
mlirContextGetOrLoadDialect()
MlirDialect mlirContextGetOrLoadDialect (MlirContext context, MlirStringRef name)
Gets the dialect instance owned by the given context using the dialect namespace to identify it, loads (i.e., constructs the instance of) the dialect if necessary.
If the dialect is not registered with the context, returns null. Use mlirContextLoad<Name>Dialect to load an unregistered dialect.
Definition at line 56 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirContextIsNull().
mlirContextIsNull()
int mlirContextIsNull (MlirContext context) inline
Checks whether a context is null.
Definition at line 95 of file IR.h.
References mlirContextDestroy(), mlirContextGetAllowUnregisteredDialects(), mlirContextGetNumLoadedDialects(), mlirContextGetNumRegisteredDialects(), mlirContextGetOrLoadDialect(), mlirContextSetAllowUnregisteredDialects(), mlirDialectEqual(), mlirDialectGetContext(), mlirDialectGetNamespace(), mlirDialectIsNull(), mlirLocationFileLineColGet(), mlirLocationGetContext(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleGetContext(), and MlirNamedAttribute::name.
Referenced by mlir::python::PyMlirContext::createFromCapsule().
mlirContextSetAllowUnregisteredDialects()
void mlirContextSetAllowUnregisteredDialects (MlirContext context, int allow)
Sets whether unregistered dialects are allowed in this context.
Definition at line 39 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PyType::operator==().
mlirDialectEqual()
int mlirDialectEqual (MlirDialect dialect1, MlirDialect dialect2)
Checks if two dialects that belong to the same context are equal.
Dialects from different contexts will not compare equal.
Definition at line 73 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull().
mlirDialectGetContext()
MlirContext mlirDialectGetContext (MlirDialect dialect)
Returns the context that owns the dialect.
Definition at line 65 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirContextIsNull().
mlirDialectGetNamespace()
MlirStringRef mlirDialectGetNamespace (MlirDialect dialect)
Returns the namespace of the given dialect.
Definition at line 77 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirContextIsNull().
mlirDialectIsNull()
int mlirDialectIsNull (MlirDialect dialect)
Checks if the dialect is null.
Definition at line 69 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull().
mlirLocationFileLineColGet()
MlirLocation mlirLocationFileLineColGet (MlirContext context, const char * filename, unsigned line, unsigned col)
Creates an File/Line/Column location owned by the given context.
Definition at line 85 of file IR.cpp.
References mlir::FileLineColLoc::get(), unwrap(), and wrap().
Referenced by mlirContextIsNull(), and mlir::python::PyType::operator==().
mlirLocationGetContext()
MlirContext mlirLocationGetContext (MlirLocation location)
Gets the context that a location was created with.
Definition at line 95 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirContextIsNull().
mlirLocationPrint()
void mlirLocationPrint (MlirLocation location, MlirStringCallback callback, void * userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 99 of file IR.cpp.
References unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PyType::operator==().
mlirLocationUnknownGet()
MlirLocation mlirLocationUnknownGet (MlirContext context)
Creates a location with unknown position owned by the given context.
Definition at line 91 of file IR.cpp.
References mlir::UnknownLoc::get(), unwrap(), and wrap().
Referenced by mlirContextIsNull(), and mlir::python::PyType::operator==().
mlirModuleCreateEmpty()
MlirModule mlirModuleCreateEmpty (MlirLocation location)
Creates a new, empty module and transfers ownership to the caller.
Definition at line 110 of file IR.cpp.
References mlir::ModuleOp::create(), unwrap(), and wrap().
Referenced by mlirContextIsNull().
mlirModuleCreateParse()
MlirModule mlirModuleCreateParse (MlirContext context, const char * module)
Parses a module from the string and transfers ownership to the caller.
Definition at line 114 of file IR.cpp.
References mlir::Op< ConcreteType, Traits >::getOperation(), mlir::parseSourceString(), mlir::OwningOpRefBase< OpTy >::release(), and unwrap().
Referenced by mlirContextIsNull(), and mlir::python::PyType::operator==().
mlirModuleDestroy()
void mlirModuleDestroy (MlirModule module)
Takes a module owned by the caller and deletes it.
Definition at line 125 of file IR.cpp.
References unwrap().
Referenced by mlirModuleIsNull(), and mlir::python::PyModule::~PyModule().
mlirModuleGetContext()
MlirContext mlirModuleGetContext (MlirModule module)
Gets the context that a module was created with.
Definition at line 121 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirContextIsNull().
mlirModuleGetOperation()
MlirOperation mlirModuleGetOperation (MlirModule module)
Views the module as a generic operation.
Definition at line 130 of file IR.cpp.
References unwrap(), and wrap().
Referenced by mlirModuleIsNull(), and mlir::python::PyType::operator==().
mlirModuleIsNull()
int mlirModuleIsNull (MlirModule module) inline
Checks whether a module is null.
Definition at line 174 of file IR.h.
References mlirModuleDestroy(), and mlirModuleGetOperation().
Referenced by mlir::python::PyType::operator==().
mlirNamedAttributeGet()
MlirNamedAttribute mlirNamedAttributeGet (const char * name, MlirAttribute attr)
Associates an attribute with the name.
Takes ownership of neither.
Definition at line 473 of file IR.cpp.
Referenced by mlir::python::PyMlirContext::createOperation(), mlirAttributeIsNull(), and mlir::python::PyNamedAttribute::PyNamedAttribute().
mlirOperationCreate()
MlirOperation mlirOperationCreate (const MlirOperationState * state)
Creates an operation and transfers ownership to the caller.
Definition at line 187 of file IR.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addSuccessors(), mlir::OperationState::addTypes(), MlirNamedAttribute::attribute, MlirOperationState::attributes, mlir::OperationState::attributes, mlir::Operation::create(), MlirOperationState::location, MlirNamedAttribute::name, MlirOperationState::name, MlirOperationState::nAttributes, MlirOperationState::nOperands, MlirOperationState::nRegions, MlirOperationState::nResults, MlirOperationState::nSuccessors, MlirOperationState::operands, MlirOperationState::regions, mlir::NamedAttrList::reserve(), MlirOperationState::results, MlirOperationState::successors, unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOperationDestroy()
void mlirOperationDestroy (MlirOperation op)
Takes an operation owned by the caller and destroys it.
Definition at line 216 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyOperation::~PyOperation().
mlirOperationDump()
void mlirOperationDump (MlirOperation op)
Prints an operation to stderr.
Definition at line 277 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirOperationGetAttribute()
MlirNamedAttribute mlirOperationGetAttribute (MlirOperation op, intptr_t pos)
Return pos-th attribute of the operation.
Definition at line 260 of file IR.cpp.
References unwrap(), and wrap().
mlirOperationGetAttributeByName()
MlirAttribute mlirOperationGetAttributeByName (MlirOperation op, const char * name)
Returns an attribute attached to the operation given its name.
Definition at line 265 of file IR.cpp.
References unwrap(), and wrap().
mlirOperationGetNextInBlock()
MlirOperation mlirOperationGetNextInBlock (MlirOperation op)
Returns an operation immediately following the given operation it its enclosing block.
Definition at line 228 of file IR.cpp.
References unwrap(), and wrap().
mlirOperationGetNumAttributes()
intptr_t mlirOperationGetNumAttributes (MlirOperation op)
Returns the number of attributes attached to the operation.
Definition at line 256 of file IR.cpp.
References unwrap().
mlirOperationGetNumOperands()
intptr_t mlirOperationGetNumOperands (MlirOperation op)
Returns the number of operands of the operation.
Definition at line 232 of file IR.cpp.
References unwrap().
mlirOperationGetNumRegions()
intptr_t mlirOperationGetNumRegions (MlirOperation op)
Returns the number of regions attached to the given operation.
Definition at line 220 of file IR.cpp.
References unwrap().
mlirOperationGetNumResults()
intptr_t mlirOperationGetNumResults (MlirOperation op)
Returns the number of results of the operation.
Definition at line 240 of file IR.cpp.
References unwrap().
mlirOperationGetNumSuccessors()
intptr_t mlirOperationGetNumSuccessors (MlirOperation op)
Returns the number of successor blocks of the operation.
Definition at line 248 of file IR.cpp.
References unwrap().
mlirOperationGetOperand()
MlirValue mlirOperationGetOperand (MlirOperation op, intptr_t pos)
Returns pos-th operand of the operation.
Definition at line 236 of file IR.cpp.
References unwrap(), and wrap().
mlirOperationGetRegion()
MlirRegion mlirOperationGetRegion (MlirOperation op, intptr_t pos)
Returns pos-th region attached to the operation.
Definition at line 224 of file IR.cpp.
References unwrap(), and wrap().
mlirOperationGetResult()
MlirValue mlirOperationGetResult (MlirOperation op, intptr_t pos)
Returns pos-th result of the operation.
Definition at line 244 of file IR.cpp.
References unwrap(), and wrap().
mlirOperationGetSuccessor()
MlirBlock mlirOperationGetSuccessor (MlirOperation op, intptr_t pos)
Returns pos-th successor of the operation.
Definition at line 252 of file IR.cpp.
References unwrap(), and wrap().
mlirOperationIsNull()
int mlirOperationIsNull (MlirOperation op)
Checks whether the underlying operation is null.
Definition at line 218 of file IR.cpp.
References unwrap().
Referenced by mlirBlockInsertOwnedOperationAfter(), and mlirBlockInsertOwnedOperationBefore().
mlirOperationPrint()
void mlirOperationPrint (MlirOperation op, MlirStringCallback callback, void * userData)
Prints an operation by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 270 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirOperationStateAddAttributes()
void mlirOperationStateAddAttributes (MlirOperationState * state, intptr_t n, MlirNamedAttribute * attributes)
Definition at line 178 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOperationStateAddOperands()
void mlirOperationStateAddOperands (MlirOperationState * state, intptr_t n, MlirValue * operands)
Definition at line 166 of file IR.cpp.
References APPEND_ELEMS.
mlirOperationStateAddOwnedRegions()
void mlirOperationStateAddOwnedRegions (MlirOperationState * state, intptr_t n, MlirRegion * regions)
Definition at line 170 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOperationStateAddResults()
void mlirOperationStateAddResults (MlirOperationState * state, intptr_t n, MlirType * results)
Adds a list of components to the operation state.
Definition at line 161 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOperationStateAddSuccessors()
void mlirOperationStateAddSuccessors (MlirOperationState * state, intptr_t n, MlirBlock * successors)
Definition at line 174 of file IR.cpp.
References APPEND_ELEMS.
Referenced by mlir::python::PyMlirContext::createOperation().
mlirOperationStateGet()
MlirOperationState mlirOperationStateGet (const char * name, MlirLocation loc)
Constructs an operation state from a name and a location.
Definition at line 138 of file IR.cpp.
References MlirOperationState::attributes, MlirOperationState::location, MlirOperationState::name, MlirOperationState::nAttributes, MlirOperationState::nOperands, MlirOperationState::nRegions, MlirOperationState::nResults, MlirOperationState::nSuccessors, MlirOperationState::operands, MlirOperationState::regions, MlirOperationState::results, and MlirOperationState::successors.
Referenced by mlir::python::PyMlirContext::createOperation().
mlirRegionAppendOwnedBlock()
void mlirRegionAppendOwnedBlock (MlirRegion region, MlirBlock block)
Takes a block owned by the caller and appends it to the given region.
Definition at line 292 of file IR.cpp.
References unwrap().
Referenced by mlirRegionInsertOwnedBlockBefore().
mlirRegionCreate()
MlirRegion mlirRegionCreate ()
Creates a new empty region and transfers ownership to the caller.
Definition at line 283 of file IR.cpp.
References wrap().
Referenced by mlir::python::PyMlirContext::createOperation().
mlirRegionDestroy()
void mlirRegionDestroy (MlirRegion region)
Takes a region owned by the caller and destroys it.
Definition at line 327 of file IR.cpp.
mlirRegionGetFirstBlock()
MlirBlock mlirRegionGetFirstBlock (MlirRegion region)
Gets the first block in the region.
Definition at line 285 of file IR.cpp.
References mlir::Region::empty(), mlir::Region::front(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirRegionInsertOwnedBlock()
void mlirRegionInsertOwnedBlock (MlirRegion region, intptr_t pos, MlirBlock block)
Takes a block owned by the caller and inserts it at pos to the given region.
This is an expensive operation that linearly scans the region, prefer insertAfter/Before instead.
Definition at line 296 of file IR.cpp.
References unwrap().
mlirRegionInsertOwnedBlockAfter()
void mlirRegionInsertOwnedBlockAfter (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it after the (non-owned) reference block in the given region.
The reference block must belong to the region. If the reference block is null, prepends the block to the region.
Definition at line 302 of file IR.cpp.
References mlir::Region::begin(), mlir::Region::getBlocks(), mlirBlockIsNull(), and unwrap().
mlirRegionInsertOwnedBlockBefore()
void mlirRegionInsertOwnedBlockBefore (MlirRegion region, MlirBlock reference, MlirBlock block)
Takes a block owned by the caller and inserts it before the (non-owned) reference block in the given region.
The reference block must belong to the region. If the reference block is null, appends the block to the region.
Definition at line 316 of file IR.cpp.
References mlirBlockIsNull(), mlirRegionAppendOwnedBlock(), and unwrap().
mlirRegionIsNull()
int mlirRegionIsNull (MlirRegion region)
Checks whether a region is null.
Definition at line 331 of file IR.cpp.
References unwrap().
Referenced by mlir::python::PyRegion::PyRegion().
mlirTypeDump()
void mlirTypeDump (MlirType type)
Prints the type to the standard error stream.
Definition at line 446 of file IR.cpp.
References unwrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirTypeEqual()
int mlirTypeEqual (MlirType t1, MlirType t2)
Checks if two types are equal.
Definition at line 438 of file IR.cpp.
References unwrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirTypeGetContext()
MlirContext mlirTypeGetContext (MlirType type)
Gets the context that a type was created with.
Definition at line 434 of file IR.cpp.
References unwrap(), and wrap().
mlirTypeIsNull()
int mlirTypeIsNull (MlirType type) inline
Checks whether a type is null.
Definition at line 404 of file IR.h.
References MlirNamedAttribute::attribute, mlirAttributeGetContext(), mlirAttributeParseGet(), mlirTypeDump(), mlirTypeEqual(), and mlirTypePrint().
Referenced by mlir::python::PyType::operator==().
mlirTypeParseGet()
MlirType mlirTypeParseGet (MlirContext context, const char * type)
Parses a type.
The type is owned by the context.
Definition at line 430 of file IR.cpp.
References mlir::parseType(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirTypePrint()
void mlirTypePrint (MlirType type, MlirStringCallback callback, void * userData)
Prints a location by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 440 of file IR.cpp.
References unwrap().
Referenced by mlirTypeIsNull(), and mlir::python::PyType::operator==().
mlirValueGetType()
MlirType mlirValueGetType (MlirValue value)
Returns the type of the value.
Definition at line 415 of file IR.cpp.
References unwrap(), and wrap().
mlirValuePrint()
void mlirValuePrint (MlirValue value, MlirStringCallback callback, void * userData)
Prints a value by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 419 of file IR.cpp.
References unwrap().