MLIR: include/mlir-c/Support.h File Reference
Support.h File Reference
#include <stddef.h>
#include <stdint.h>
Classes
struct MlirStringRef
A pointer to a sized fragment of a string, not necessarily null-terminated.
Typedefs
typedef struct MlirStringRef MlirStringRef
Functions
MlirStringRef mlirStringRefCreate (const char *str, size_t length)
Constructs a string reference from the pointer and length.
MlirStringRef mlirStringRefCreateFromCString (const char *str)
Constructs a string reference from a null-terminated C string.
Typedef Documentation
MlirStringRef
typedef struct MlirStringRef MlirStringRef
Definition at line 36 of file Support.h.
Function Documentation
mlirStringRefCreate()
MlirStringRef mlirStringRefCreate (const char * str, size_t length) inline
Constructs a string reference from the pointer and length.
The pointer need not reference to a null-terminated string.
Definition at line 41 of file Support.h.
References MlirStringRef::data, MlirStringRef::length, and mlirStringRefCreateFromCString().
Referenced by mlirStringRefCreateFromCString(), and wrap().
mlirStringRefCreateFromCString()
MlirStringRef mlirStringRefCreateFromCString (const char * str)
Constructs a string reference from a null-terminated C string.
Prefer mlirStringRefCreate if the length of the string is known.
Definition at line 13 of file Support.cpp.
References mlirStringRefCreate().
Referenced by mlirStringRefCreate().