MLIR: include/mlir-c/StandardTypes.h File Reference
StandardTypes.h File Reference
#include "mlir-c/AffineMap.h"
#include "mlir-c/IR.h"
#include <stdint.h>
Functions
int mlirTypeIsAInteger (MlirType type)
Checks whether the given type is an integer type.
MlirType mlirIntegerTypeGet (MlirContext ctx, unsigned bitwidth)
Creates a signless integer type of the given bitwidth in the context.
MlirType mlirIntegerTypeSignedGet (MlirContext ctx, unsigned bitwidth)
Creates a signed integer type of the given bitwidth in the context.
MlirType mlirIntegerTypeUnsignedGet (MlirContext ctx, unsigned bitwidth)
Creates an unsigned integer type of the given bitwidth in the context.
unsigned mlirIntegerTypeGetWidth (MlirType type)
Returns the bitwidth of an integer type.
int mlirIntegerTypeIsSignless (MlirType type)
Checks whether the given integer type is signless.
int mlirIntegerTypeIsSigned (MlirType type)
Checks whether the given integer type is signed.
int mlirIntegerTypeIsUnsigned (MlirType type)
Checks whether the given integer type is unsigned.
int mlirTypeIsAIndex (MlirType type)
Checks whether the given type is an index type.
MlirType mlirIndexTypeGet (MlirContext ctx)
Creates an index type in the given context.
int mlirTypeIsABF16 (MlirType type)
Checks whether the given type is a bf16 type.
MlirType mlirBF16TypeGet (MlirContext ctx)
Creates a bf16 type in the given context.
int mlirTypeIsAF16 (MlirType type)
Checks whether the given type is an f16 type.
MlirType mlirF16TypeGet (MlirContext ctx)
Creates an f16 type in the given context.
int mlirTypeIsAF32 (MlirType type)
Checks whether the given type is an f32 type.
MlirType mlirF32TypeGet (MlirContext ctx)
Creates an f32 type in the given context.
int mlirTypeIsAF64 (MlirType type)
Checks whether the given type is an f64 type.
MlirType mlirF64TypeGet (MlirContext ctx)
Creates a f64 type in the given context.
int mlirTypeIsANone (MlirType type)
Checks whether the given type is a None type.
MlirType mlirNoneTypeGet (MlirContext ctx)
Creates a None type in the given context.
int mlirTypeIsAComplex (MlirType type)
Checks whether the given type is a Complex type.
MlirType mlirComplexTypeGet (MlirType elementType)
Creates a complex type with the given element type in the same context as the element type.
MlirType mlirComplexTypeGetElementType (MlirType type)
Returns the element type of the given complex type.
int mlirTypeIsAShaped (MlirType type)
Checks whether the given type is a Shaped type.
MlirType mlirShapedTypeGetElementType (MlirType type)
Returns the element type of the shaped type.
int mlirShapedTypeHasRank (MlirType type)
Checks whether the given shaped type is ranked.
int64_t mlirShapedTypeGetRank (MlirType type)
Returns the rank of the given ranked shaped type.
int mlirShapedTypeHasStaticShape (MlirType type)
Checks whether the given shaped type has a static shape.
int mlirShapedTypeIsDynamicDim (MlirType type, intptr_t dim)
Checks wither the dim-th dimension of the given shaped type is dynamic.
int64_t mlirShapedTypeGetDimSize (MlirType type, intptr_t dim)
Returns the dim-th dimension of the given ranked shaped type.
int mlirShapedTypeIsDynamicSize (int64_t size)
Checks whether the given value is used as a placeholder for dynamic sizes in shaped types.
int mlirShapedTypeIsDynamicStrideOrOffset (int64_t val)
Checks whether the given value is used as a placeholder for dynamic strides and offsets in shaped types.
int mlirTypeIsAVector (MlirType type)
Checks whether the given type is a Vector type.
MlirType mlirVectorTypeGet (intptr_t rank, int64_t *shape, MlirType elementType)
Creates a vector type of the shape identified by its rank and dimensions, with the given element type in the same context as the element type.
MlirType mlirVectorTypeGetChecked (intptr_t rank, int64_t *shape, MlirType elementType, MlirLocation loc)
Same as "mlirVectorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
int mlirTypeIsATensor (MlirType type)
Checks whether the given type is a Tensor type.
int mlirTypeIsARankedTensor (MlirType type)
Checks whether the given type is a ranked tensor type.
int mlirTypeIsAUnrankedTensor (MlirType type)
Checks whether the given type is an unranked tensor type.
MlirType mlirRankedTensorTypeGet (intptr_t rank, int64_t *shape, MlirType elementType)
Creates a tensor type of a fixed rank with the given shape and element type in the same context as the element type.
MlirType mlirRankedTensorTypeGetChecked (intptr_t rank, int64_t *shape, MlirType elementType, MlirLocation loc)
Same as "mlirRankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MlirType mlirUnrankedTensorTypeGet (MlirType elementType)
Creates an unranked tensor type with the given element type in the same context as the element type.
MlirType mlirUnrankedTensorTypeGetChecked (MlirType elementType, MlirLocation loc)
Same as "mlirUnrankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
int mlirTypeIsAMemRef (MlirType type)
Checks whether the given type is a MemRef type.
int mlirTypeIsAUnrankedMemRef (MlirType type)
Checks whether the given type is an UnrankedMemRef type.
MlirType mlirMemRefTypeGet (MlirType elementType, intptr_t rank, int64_t *shape, intptr_t numMaps, MlirAttribute *affineMaps, unsigned memorySpace)
Creates a MemRef type with the given rank and shape, a potentially empty list of affine layout maps, the given memory space and element type, in the same context as element type.
MlirType mlirMemRefTypeContiguousGet (MlirType elementType, intptr_t rank, int64_t *shape, unsigned memorySpace)
Creates a MemRef type with the given rank, shape, memory space and element type in the same context as the element type.
MlirType mlirMemRefTypeContiguousGetChecked (MlirType elementType, intptr_t rank, int64_t *shape, unsigned memorySpace, MlirLocation loc)
Same as "mlirMemRefTypeContiguousGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
MlirType mlirUnrankedMemRefTypeGet (MlirType elementType, unsigned memorySpace)
Creates an Unranked MemRef type with the given element type and in the given memory space.
MlirType mlirUnrankedMemRefTypeGetChecked (MlirType elementType, unsigned memorySpace, MlirLocation loc)
Same as "mlirUnrankedMemRefTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
intptr_t mlirMemRefTypeGetNumAffineMaps (MlirType type)
Returns the number of affine layout maps in the given MemRef type.
MlirAffineMap mlirMemRefTypeGetAffineMap (MlirType type, intptr_t pos)
Returns the pos-th affine map of the given MemRef type.
unsigned mlirMemRefTypeGetMemorySpace (MlirType type)
Returns the memory space of the given MemRef type.
unsigned mlirUnrankedMemrefGetMemorySpace (MlirType type)
Returns the memory spcae of the given Unranked MemRef type.
int mlirTypeIsATuple (MlirType type)
Checks whether the given type is a tuple type.
MlirType mlirTupleTypeGet (MlirContext ctx, intptr_t numElements, MlirType *elements)
Creates a tuple type that consists of the given list of elemental types.
intptr_t mlirTupleTypeGetNumTypes (MlirType type)
Returns the number of types contained in a tuple.
MlirType mlirTupleTypeGetType (MlirType type, intptr_t pos)
Returns the pos-th type in the tuple type.
int mlirTypeIsAFunction (MlirType type)
Checks whether the given type is a function type.
MlirType mlirFunctionTypeGet (MlirContext ctx, intptr_t numInputs, MlirType *inputs, intptr_t numResults, MlirType *results)
Creates a function type, mapping a list of input types to result types.
intptr_t mlirFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
intptr_t mlirFunctionTypeGetNumResults (MlirType type)
Returns the number of result types.
MlirType mlirFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
MlirType mlirFunctionTypeGetResult (MlirType type, intptr_t pos)
Returns the pos-th result type.
Function Documentation
mlirBF16TypeGet()
MlirType mlirBF16TypeGet (MlirContext ctx)
Creates a bf16 type in the given context.
The type is owned by the context.
Definition at line 72 of file StandardTypes.cpp.
References mlir::FloatType::getBF16(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirComplexTypeGet()
MlirType mlirComplexTypeGet (MlirType elementType)
Creates a complex type with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 112 of file StandardTypes.cpp.
References mlir::ComplexType::get(), unwrap(), and wrap().
mlirComplexTypeGetElementType()
MlirType mlirComplexTypeGetElementType (MlirType type)
Returns the element type of the given complex type.
Definition at line 116 of file StandardTypes.cpp.
References getElementType(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirF16TypeGet()
MlirType mlirF16TypeGet (MlirContext ctx)
Creates an f16 type in the given context.
The type is owned by the context.
Definition at line 78 of file StandardTypes.cpp.
References mlir::FloatType::getF16(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirF32TypeGet()
MlirType mlirF32TypeGet (MlirContext ctx)
Creates an f32 type in the given context.
The type is owned by the context.
Definition at line 84 of file StandardTypes.cpp.
References mlir::FloatType::getF32(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirF64TypeGet()
MlirType mlirF64TypeGet (MlirContext ctx)
Creates a f64 type in the given context.
The type is owned by the context.
Definition at line 90 of file StandardTypes.cpp.
References mlir::FloatType::getF64(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirFunctionTypeGet()
MlirType mlirFunctionTypeGet (MlirContext ctx, intptr_t numInputs, MlirType * inputs, intptr_t numResults, MlirType * results)
Creates a function type, mapping a list of input types to result types.
Definition at line 310 of file StandardTypes.cpp.
References mlir::FunctionType::get(), unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirFunctionTypeGetInput()
MlirType mlirFunctionTypeGetInput (MlirType type, intptr_t pos)
Returns the pos-th input type.
Definition at line 328 of file StandardTypes.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirFunctionTypeGetNumInputs()
intptr_t mlirFunctionTypeGetNumInputs (MlirType type)
Returns the number of input types.
Definition at line 320 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirFunctionTypeGetNumResults()
intptr_t mlirFunctionTypeGetNumResults (MlirType type)
Returns the number of result types.
Definition at line 324 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirFunctionTypeGetResult()
MlirType mlirFunctionTypeGetResult (MlirType type, intptr_t pos)
Returns the pos-th result type.
Definition at line 334 of file StandardTypes.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirIndexTypeGet()
MlirType mlirIndexTypeGet (MlirContext ctx)
Creates an index type in the given context.
The type is owned by the context.
Definition at line 62 of file StandardTypes.cpp.
References mlir::IndexType::get(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeGet()
MlirType mlirIntegerTypeGet (MlirContext ctx, unsigned bitwidth)
Creates a signless integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 28 of file StandardTypes.cpp.
References mlir::IntegerType::get(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeGetWidth()
unsigned mlirIntegerTypeGetWidth (MlirType type)
Returns the bitwidth of an integer type.
Definition at line 40 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeIsSigned()
int mlirIntegerTypeIsSigned (MlirType type)
Checks whether the given integer type is signed.
Definition at line 48 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeIsSignless()
int mlirIntegerTypeIsSignless (MlirType type)
Checks whether the given integer type is signless.
Definition at line 44 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeIsUnsigned()
int mlirIntegerTypeIsUnsigned (MlirType type)
Checks whether the given integer type is unsigned.
Definition at line 52 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeSignedGet()
MlirType mlirIntegerTypeSignedGet (MlirContext ctx, unsigned bitwidth)
Creates a signed integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 32 of file StandardTypes.cpp.
References mlir::IntegerType::get(), mlir::IntegerType::Signed, unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirIntegerTypeUnsignedGet()
MlirType mlirIntegerTypeUnsignedGet (MlirContext ctx, unsigned bitwidth)
Creates an unsigned integer type of the given bitwidth in the context.
The type is owned by the context.
Definition at line 36 of file StandardTypes.cpp.
References mlir::IntegerType::get(), mlir::IntegerType::Unsigned, unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirMemRefTypeContiguousGet()
MlirType mlirMemRefTypeContiguousGet (MlirType elementType, intptr_t rank, int64_t * shape, unsigned memorySpace)
Creates a MemRef type with the given rank, shape, memory space and element type in the same context as the element type.
The type has no affine maps, i.e. represents a default row-major contiguous memref. The type is owned by the context.
Definition at line 233 of file StandardTypes.cpp.
References mlir::MemRefType::get(), unwrap(), and wrap().
mlirMemRefTypeContiguousGetChecked()
MlirType mlirMemRefTypeContiguousGetChecked (MlirType elementType, intptr_t rank, int64_t * shape, unsigned memorySpace, MlirLocation loc)
Same as "mlirMemRefTypeContiguousGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 240 of file StandardTypes.cpp.
References mlir::MemRefType::getChecked(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirMemRefTypeGet()
MlirType mlirMemRefTypeGet (MlirType elementType, intptr_t rank, int64_t * shape, intptr_t numMaps, MlirAttribute * affineMaps, unsigned memorySpace)
Creates a MemRef type with the given rank and shape, a potentially empty list of affine layout maps, the given memory space and element type, in the same context as element type.
The type is owned by the context.
mlirMemRefTypeGetAffineMap()
MlirAffineMap mlirMemRefTypeGetAffineMap (MlirType type, intptr_t pos)
Returns the pos-th affine map of the given MemRef type.
Definition at line 254 of file StandardTypes.cpp.
References getAffineMaps(), unwrap(), and wrap().
mlirMemRefTypeGetMemorySpace()
unsigned mlirMemRefTypeGetMemorySpace (MlirType type)
Returns the memory space of the given MemRef type.
Definition at line 258 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirMemRefTypeGetNumAffineMaps()
intptr_t mlirMemRefTypeGetNumAffineMaps (MlirType type)
Returns the number of affine layout maps in the given MemRef type.
Definition at line 249 of file StandardTypes.cpp.
References getAffineMaps(), and unwrap().
Referenced by mlir::python::PyType::operator==().
mlirNoneTypeGet()
MlirType mlirNoneTypeGet (MlirContext ctx)
Creates a None type in the given context.
The type is owned by the context.
Definition at line 100 of file StandardTypes.cpp.
References mlir::NoneType::get(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirRankedTensorTypeGet()
MlirType mlirRankedTensorTypeGet (intptr_t rank, int64_t * shape, MlirType elementType)
Creates a tensor type of a fixed rank with the given shape and element type in the same context as the element type.
The type is owned by the context.
Definition at line 193 of file StandardTypes.cpp.
References mlir::RankedTensorType::get(), unwrap(), and wrap().
mlirRankedTensorTypeGetChecked()
MlirType mlirRankedTensorTypeGetChecked (intptr_t rank, int64_t * shape, MlirType elementType, MlirLocation loc)
Same as "mlirRankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 200 of file StandardTypes.cpp.
References mlir::RankedTensorType::getChecked(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirShapedTypeGetDimSize()
int64_t mlirShapedTypeGetDimSize (MlirType type, intptr_t dim)
Returns the dim-th dimension of the given ranked shaped type.
Definition at line 147 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirShapedTypeGetElementType()
MlirType mlirShapedTypeGetElementType (MlirType type)
Returns the element type of the shaped type.
Definition at line 126 of file StandardTypes.cpp.
References getElementType(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirShapedTypeGetRank()
int64_t mlirShapedTypeGetRank (MlirType type)
Returns the rank of the given ranked shaped type.
Definition at line 134 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirShapedTypeHasRank()
int mlirShapedTypeHasRank (MlirType type)
Checks whether the given shaped type is ranked.
Definition at line 130 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirShapedTypeHasStaticShape()
int mlirShapedTypeHasStaticShape (MlirType type)
Checks whether the given shaped type has a static shape.
Definition at line 138 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirShapedTypeIsDynamicDim()
int mlirShapedTypeIsDynamicDim (MlirType type, intptr_t dim)
Checks wither the dim-th dimension of the given shaped type is dynamic.
Definition at line 142 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirShapedTypeIsDynamicSize()
int mlirShapedTypeIsDynamicSize (int64_t size)
Checks whether the given value is used as a placeholder for dynamic sizes in shaped types.
Definition at line 151 of file StandardTypes.cpp.
References mlir::ShapedType::isDynamic().
Referenced by mlir::python::PyType::operator==().
mlirShapedTypeIsDynamicStrideOrOffset()
int mlirShapedTypeIsDynamicStrideOrOffset (int64_t val)
Checks whether the given value is used as a placeholder for dynamic strides and offsets in shaped types.
Definition at line 155 of file StandardTypes.cpp.
References mlir::ShapedType::isDynamicStrideOrOffset().
Referenced by mlir::python::PyType::operator==().
mlirTupleTypeGet()
MlirType mlirTupleTypeGet (MlirContext ctx, intptr_t numElements, MlirType * elements)
Creates a tuple type that consists of the given list of elemental types.
The type is owned by the context.
Definition at line 287 of file StandardTypes.cpp.
References mlir::TupleType::get(), unwrap(), unwrapList(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirTupleTypeGetNumTypes()
intptr_t mlirTupleTypeGetNumTypes (MlirType type)
Returns the number of types contained in a tuple.
Definition at line 294 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTupleTypeGetType()
MlirType mlirTupleTypeGetType (MlirType type, intptr_t pos)
Returns the pos-th type in the tuple type.
Definition at line 298 of file StandardTypes.cpp.
References unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsABF16()
int mlirTypeIsABF16 (MlirType type)
Checks whether the given type is a bf16 type.
Definition at line 70 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAComplex()
int mlirTypeIsAComplex (MlirType type)
Checks whether the given type is a Complex type.
Definition at line 108 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAF16()
int mlirTypeIsAF16 (MlirType type)
Checks whether the given type is an f16 type.
Definition at line 76 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAF32()
int mlirTypeIsAF32 (MlirType type)
Checks whether the given type is an f32 type.
Definition at line 82 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAF64()
int mlirTypeIsAF64 (MlirType type)
Checks whether the given type is an f64 type.
Definition at line 88 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAFunction()
int mlirTypeIsAFunction (MlirType type)
Checks whether the given type is a function type.
Definition at line 306 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAIndex()
int mlirTypeIsAIndex (MlirType type)
Checks whether the given type is an index type.
Definition at line 60 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAInteger()
int mlirTypeIsAInteger (MlirType type)
Checks whether the given type is an integer type.
Definition at line 24 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAMemRef()
int mlirTypeIsAMemRef (MlirType type)
Checks whether the given type is a MemRef type.
Definition at line 221 of file StandardTypes.cpp.
References unwrap().
mlirTypeIsANone()
int mlirTypeIsANone (MlirType type)
Checks whether the given type is a None type.
Definition at line 98 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsARankedTensor()
int mlirTypeIsARankedTensor (MlirType type)
Checks whether the given type is a ranked tensor type.
Definition at line 185 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAShaped()
int mlirTypeIsAShaped (MlirType type)
Checks whether the given type is a Shaped type.
Definition at line 124 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsATensor()
int mlirTypeIsATensor (MlirType type)
Checks whether the given type is a Tensor type.
Definition at line 183 of file StandardTypes.cpp.
References unwrap().
mlirTypeIsATuple()
int mlirTypeIsATuple (MlirType type)
Checks whether the given type is a tuple type.
Definition at line 285 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAUnrankedMemRef()
int mlirTypeIsAUnrankedMemRef (MlirType type)
Checks whether the given type is an UnrankedMemRef type.
Definition at line 262 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAUnrankedTensor()
int mlirTypeIsAUnrankedTensor (MlirType type)
Checks whether the given type is an unranked tensor type.
Definition at line 189 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirTypeIsAVector()
int mlirTypeIsAVector (MlirType type)
Checks whether the given type is a Vector type.
Definition at line 163 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirUnrankedMemrefGetMemorySpace()
unsigned mlirUnrankedMemrefGetMemorySpace (MlirType type)
Returns the memory spcae of the given Unranked MemRef type.
Definition at line 277 of file StandardTypes.cpp.
References unwrap().
Referenced by mlir::python::PyType::operator==().
mlirUnrankedMemRefTypeGet()
MlirType mlirUnrankedMemRefTypeGet (MlirType elementType, unsigned memorySpace)
Creates an Unranked MemRef type with the given element type and in the given memory space.
The type is owned by the context of element type.
Definition at line 266 of file StandardTypes.cpp.
References mlir::UnrankedMemRefType::get(), unwrap(), and wrap().
mlirUnrankedMemRefTypeGetChecked()
MlirType mlirUnrankedMemRefTypeGetChecked (MlirType elementType, unsigned memorySpace, MlirLocation loc)
Same as "mlirUnrankedMemRefTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 270 of file StandardTypes.cpp.
References mlir::UnrankedMemRefType::getChecked(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirUnrankedTensorTypeGet()
MlirType mlirUnrankedTensorTypeGet (MlirType elementType)
Creates an unranked tensor type with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 208 of file StandardTypes.cpp.
References mlir::UnrankedTensorType::get(), unwrap(), and wrap().
mlirUnrankedTensorTypeGetChecked()
MlirType mlirUnrankedTensorTypeGetChecked (MlirType elementType, MlirLocation loc)
Same as "mlirUnrankedTensorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 212 of file StandardTypes.cpp.
References mlir::UnrankedTensorType::getChecked(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().
mlirVectorTypeGet()
MlirType mlirVectorTypeGet (intptr_t rank, int64_t * shape, MlirType elementType)
Creates a vector type of the shape identified by its rank and dimensions, with the given element type in the same context as the element type.
The type is owned by the context.
Definition at line 165 of file StandardTypes.cpp.
References mlir::VectorType::get(), unwrap(), and wrap().
mlirVectorTypeGetChecked()
MlirType mlirVectorTypeGetChecked (intptr_t rank, int64_t * shape, MlirType elementType, MlirLocation loc)
Same as "mlirVectorTypeGet" but returns a nullptr wrapping MlirType on illegal arguments, emitting appropriate diagnostics.
Definition at line 172 of file StandardTypes.cpp.
References mlir::VectorType::getChecked(), unwrap(), and wrap().
Referenced by mlir::python::PyType::operator==().