MLIR: include/mlir/CAPI/Support.h File Reference
Support.h File Reference
#include "mlir-c/Support.h"
#include "llvm/ADT/StringRef.h"
Functions
MlirStringRef wrap (llvm::StringRef ref)
Converts a StringRef into its MLIR C API equivalent.
llvm::StringRef unwrap (MlirStringRef ref)
Creates a StringRef out of its MLIR C API equivalent.
Function Documentation
unwrap()
llvm::StringRef unwrap (MlirStringRef ref) inline
Creates a StringRef out of its MLIR C API equivalent.
Definition at line 27 of file Support.h.
References MlirStringRef::data, and MlirStringRef::length.
Referenced by llvm::GraphTraits< const mlir::CallGraphNode * >::child_begin(), llvm::GraphTraits< const mlir::CallGraphNode * >::child_end(), getDenseAttribute(), mlirAffineMapAttrGet(), mlirAffineMapAttrGetValue(), mlirAffineMapConstantGet(), mlirAffineMapDump(), mlirAffineMapEmptyGet(), mlirAffineMapEqual(), mlirAffineMapGet(), mlirAffineMapGetContext(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetNumDims(), mlirAffineMapGetNumInputs(), mlirAffineMapGetNumResults(), mlirAffineMapGetNumSymbols(), mlirAffineMapGetSingleConstantResult(), mlirAffineMapGetSubMap(), mlirAffineMapIsEmpty(), mlirAffineMapIsIdentity(), mlirAffineMapIsMinorIdentity(), mlirAffineMapIsPermutation(), mlirAffineMapIsProjectedPermutation(), mlirAffineMapIsSingleConstant(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), mlirAffineMapPrint(), mlirArrayAttrGet(), mlirArrayAttrGetElement(), mlirArrayAttrGetNumElements(), mlirAttributeDump(), mlirAttributeEqual(), mlirAttributeGetContext(), mlirAttributeIsAAffineMap(), mlirAttributeIsAArray(), mlirAttributeIsABool(), mlirAttributeIsADenseElements(), mlirAttributeIsADenseFPElements(), mlirAttributeIsADenseIntElements(), mlirAttributeIsADictionary(), mlirAttributeIsAElements(), mlirAttributeIsAFlatSymbolRef(), mlirAttributeIsAFloat(), mlirAttributeIsAInteger(), mlirAttributeIsAIntegerSet(), mlirAttributeIsAOpaque(), mlirAttributeIsAOpaqueElements(), mlirAttributeIsASparseElements(), mlirAttributeIsAString(), mlirAttributeIsASymbolRef(), mlirAttributeIsAType(), mlirAttributeIsAUnit(), mlirAttributeParseGet(), mlirAttributePrint(), mlirBF16TypeGet(), mlirBlockAppendOwnedOperation(), mlirBlockCreate(), mlirBlockDestroy(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNextInRegion(), mlirBlockGetNumArguments(), mlirBlockInsertOwnedOperation(), mlirBlockInsertOwnedOperationAfter(), mlirBlockInsertOwnedOperationBefore(), mlirBlockIsNull(), mlirBlockPrint(), mlirBoolAttrGet(), mlirBoolAttrGetValue(), mlirComplexTypeGet(), mlirComplexTypeGetElementType(), mlirContextDestroy(), mlirContextEqual(), mlirContextGetAllowUnregisteredDialects(), mlirContextGetNumLoadedDialects(), mlirContextGetNumRegisteredDialects(), mlirContextGetOrLoadDialect(), mlirContextLoadStandardDialect(), mlirContextRegisterStandardDialect(), mlirContextSetAllowUnregisteredDialects(), mlirDenseElementsAttrBoolGet(), mlirDenseElementsAttrBoolSplatGet(), mlirDenseElementsAttrDoubleSplatGet(), mlirDenseElementsAttrFloatSplatGet(), mlirDenseElementsAttrGet(), mlirDenseElementsAttrGetBoolSplatValue(), mlirDenseElementsAttrGetBoolValue(), mlirDenseElementsAttrGetDoubleSplatValue(), mlirDenseElementsAttrGetDoubleValue(), mlirDenseElementsAttrGetFloatSplatValue(), mlirDenseElementsAttrGetFloatValue(), mlirDenseElementsAttrGetInt32SplatValue(), mlirDenseElementsAttrGetInt32Value(), mlirDenseElementsAttrGetInt64SplatValue(), mlirDenseElementsAttrGetInt64Value(), mlirDenseElementsAttrGetSplatValue(), mlirDenseElementsAttrGetStringSplatValue(), mlirDenseElementsAttrGetStringValue(), mlirDenseElementsAttrGetUInt32SplatValue(), mlirDenseElementsAttrGetUInt32Value(), mlirDenseElementsAttrGetUInt64SplatValue(), mlirDenseElementsAttrGetUInt64Value(), mlirDenseElementsAttrInt32SplatGet(), mlirDenseElementsAttrInt64SplatGet(), mlirDenseElementsAttrIsSplat(), mlirDenseElementsAttrReshapeGet(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrStringGet(), mlirDenseElementsAttrUInt32SplatGet(), mlirDenseElementsAttrUInt64SplatGet(), mlirDialectEqual(), mlirDialectGetContext(), mlirDialectGetNamespace(), mlirDialectIsNull(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirDictionaryAttrGetNumElements(), mlirElementsAttrGetNumElements(), mlirElementsAttrGetValue(), mlirElementsAttrIsValidIndex(), mlirF16TypeGet(), mlirF32TypeGet(), mlirF64TypeGet(), mlirFlatSymbolRefAttrGet(), mlirFlatSymbolRefAttrGetValue(), mlirFloatAttrDoubleGet(), mlirFloatAttrGetValueDouble(), mlirFunctionTypeGet(), mlirFunctionTypeGetInput(), mlirFunctionTypeGetNumInputs(), mlirFunctionTypeGetNumResults(), mlirFunctionTypeGetResult(), mlirIndexTypeGet(), mlirIntegerAttrGet(), mlirIntegerAttrGetValueInt(), mlirIntegerTypeGet(), mlirIntegerTypeGetWidth(), mlirIntegerTypeIsSigned(), mlirIntegerTypeIsSignless(), mlirIntegerTypeIsUnsigned(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirLocationFileLineColGet(), mlirLocationGetContext(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirMemRefTypeContiguousGet(), mlirMemRefTypeContiguousGetChecked(), mlirMemRefTypeGet(), mlirMemRefTypeGetAffineMap(), mlirMemRefTypeGetMemorySpace(), mlirMemRefTypeGetNumAffineMaps(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleDestroy(), mlirModuleGetContext(), mlirModuleGetOperation(), mlirNoneTypeGet(), mlirOpaqueAttrGet(), mlirOpaqueAttrGetData(), mlirOpaqueAttrGetDialectNamespace(), mlirOperationCreate(), mlirOperationDestroy(), mlirOperationDump(), mlirOperationGetAttribute(), mlirOperationGetAttributeByName(), mlirOperationGetNextInBlock(), mlirOperationGetNumAttributes(), mlirOperationGetNumOperands(), mlirOperationGetNumRegions(), mlirOperationGetNumResults(), mlirOperationGetNumSuccessors(), mlirOperationGetOperand(), mlirOperationGetRegion(), mlirOperationGetResult(), mlirOperationGetSuccessor(), mlirOperationIsNull(), mlirOperationPrint(), mlirRankedTensorTypeGet(), mlirRankedTensorTypeGetChecked(), mlirRegionAppendOwnedBlock(), mlirRegionGetFirstBlock(), mlirRegionInsertOwnedBlock(), mlirRegionInsertOwnedBlockAfter(), mlirRegionInsertOwnedBlockBefore(), mlirRegionIsNull(), mlirRegisterAllDialects(), mlirShapedTypeGetDimSize(), mlirShapedTypeGetElementType(), mlirShapedTypeGetRank(), mlirShapedTypeHasRank(), mlirShapedTypeHasStaticShape(), mlirShapedTypeIsDynamicDim(), mlirSparseElementsAttrGetIndices(), mlirSparseElementsAttrGetValues(), mlirSparseElementsAttribute(), mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirSymbolRefAttrGet(), mlirSymbolRefAttrGetLeafReference(), mlirSymbolRefAttrGetNestedReference(), mlirSymbolRefAttrGetNumNestedReferences(), mlirSymbolRefAttrGetRootReference(), mlirTupleTypeGet(), mlirTupleTypeGetNumTypes(), mlirTupleTypeGetType(), mlirTypeAttrGet(), mlirTypeAttrGetValue(), mlirTypeDump(), mlirTypeEqual(), mlirTypeGetContext(), mlirTypeIsABF16(), mlirTypeIsAComplex(), mlirTypeIsAF16(), mlirTypeIsAF32(), mlirTypeIsAF64(), mlirTypeIsAFunction(), mlirTypeIsAIndex(), mlirTypeIsAInteger(), mlirTypeIsAMemRef(), mlirTypeIsANone(), mlirTypeIsARankedTensor(), mlirTypeIsAShaped(), mlirTypeIsATensor(), mlirTypeIsATuple(), mlirTypeIsAUnrankedMemRef(), mlirTypeIsAUnrankedTensor(), mlirTypeIsAVector(), mlirTypeParseGet(), mlirTypePrint(), mlirUnitAttrGet(), mlirUnrankedMemrefGetMemorySpace(), mlirUnrankedMemRefTypeGet(), mlirUnrankedMemRefTypeGetChecked(), mlirUnrankedTensorTypeGet(), mlirUnrankedTensorTypeGetChecked(), mlirValueGetType(), mlirValuePrint(), mlirVectorTypeGet(), mlirVectorTypeGetChecked(), mlir::detail::op_iterator< OpT, IteratorT >::op_iterator(), mlir::ValueTypeIterator< ValueIteratorT >::operator*(), mlir::Block::splitBlock(), unwrapList(), and mlir::tblgen::Operator::VariableDecoratorIterator::VariableDecoratorIterator().
wrap()
MlirStringRef wrap (llvm::StringRef ref) inline
Converts a StringRef into its MLIR C API equivalent.
Definition at line 22 of file Support.h.
References mlirStringRefCreate().
Referenced by getDenseAttribute(), mlirAffineMapAttrGet(), mlirAffineMapAttrGetValue(), mlirAffineMapConstantGet(), mlirAffineMapEmptyGet(), mlirAffineMapGet(), mlirAffineMapGetContext(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetSubMap(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), mlirArrayAttrGet(), mlirArrayAttrGetElement(), mlirAttributeGetContext(), mlirAttributeParseGet(), mlirBF16TypeGet(), mlirBlockCreate(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNextInRegion(), mlirBoolAttrGet(), mlirComplexTypeGet(), mlirComplexTypeGetElementType(), mlirContextCreate(), mlirContextGetOrLoadDialect(), mlirContextLoadStandardDialect(), mlirDenseElementsAttrBoolGet(), mlirDenseElementsAttrBoolSplatGet(), mlirDenseElementsAttrDoubleSplatGet(), mlirDenseElementsAttrFloatSplatGet(), mlirDenseElementsAttrGet(), mlirDenseElementsAttrGetSplatValue(), mlirDenseElementsAttrGetStringSplatValue(), mlirDenseElementsAttrGetStringValue(), mlirDenseElementsAttrInt32SplatGet(), mlirDenseElementsAttrInt64SplatGet(), mlirDenseElementsAttrReshapeGet(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrStringGet(), mlirDenseElementsAttrUInt32SplatGet(), mlirDenseElementsAttrUInt64SplatGet(), mlirDialectGetContext(), mlirDialectGetNamespace(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirElementsAttrGetValue(), mlirF16TypeGet(), mlirF32TypeGet(), mlirF64TypeGet(), mlirFlatSymbolRefAttrGet(), mlirFlatSymbolRefAttrGetValue(), mlirFloatAttrDoubleGet(), mlirFunctionTypeGet(), mlirFunctionTypeGetInput(), mlirFunctionTypeGetResult(), mlirIndexTypeGet(), mlirIntegerAttrGet(), mlirIntegerTypeGet(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirLocationFileLineColGet(), mlirLocationGetContext(), mlirLocationUnknownGet(), mlirMemRefTypeContiguousGet(), mlirMemRefTypeContiguousGetChecked(), mlirMemRefTypeGet(), mlirMemRefTypeGetAffineMap(), mlirModuleCreateEmpty(), mlirModuleGetContext(), mlirModuleGetOperation(), mlirNoneTypeGet(), mlirOpaqueAttrGet(), mlirOpaqueAttrGetData(), mlirOperationCreate(), mlirOperationGetAttribute(), mlirOperationGetAttributeByName(), mlirOperationGetNextInBlock(), mlirOperationGetOperand(), mlirOperationGetRegion(), mlirOperationGetResult(), mlirOperationGetSuccessor(), mlirRankedTensorTypeGet(), mlirRankedTensorTypeGetChecked(), mlirRegionCreate(), mlirRegionGetFirstBlock(), mlirShapedTypeGetElementType(), mlirSparseElementsAttrGetIndices(), mlirSparseElementsAttrGetValues(), mlirSparseElementsAttribute(), mlirStandardDialectGetNamespace(), mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirSymbolRefAttrGet(), mlirSymbolRefAttrGetLeafReference(), mlirSymbolRefAttrGetNestedReference(), mlirSymbolRefAttrGetRootReference(), mlirTupleTypeGet(), mlirTupleTypeGetType(), mlirTypeAttrGet(), mlirTypeAttrGetValue(), mlirTypeGetContext(), mlirTypeParseGet(), mlirUnitAttrGet(), mlirUnrankedMemRefTypeGet(), mlirUnrankedMemRefTypeGetChecked(), mlirUnrankedTensorTypeGet(), mlirUnrankedTensorTypeGetChecked(), mlirValueGetType(), mlirVectorTypeGet(), and mlirVectorTypeGetChecked().