MLIR: mlir::linalg::ConvOpVectorization< ConvOp, N > Class Template Reference
mlir::linalg::ConvOpVectorization< ConvOp, N > Class Template Reference
Converts Convolution op into vector contraction.
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
Public Member Functions
ConvOpVectorization (MLIRContext *context, SmallVector< bool, 4 > msk)
LogicalResult matchAndRewrite (ConvOp minOp, PatternRewriter &rewriter) const override
Public Member Functions inherited from mlir::OpRewritePattern< ConvOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (ConvOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (ConvOp op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
template<typename ConvOp, int N>
class mlir::linalg::ConvOpVectorization< ConvOp, N >
Converts Convolution op into vector contraction.
Conversion expects ConvOp to have dimensions marked in the mask as false of size 1. This ensures that the ConvOp can be lowered to vector contraction of dimensions marked in the mask as true.
A good example for vectorization is ConvNHWCOp which is 2D Conv op with channels as the last dimension. Let's vectorize last 3 dimensions. The initial op definition looks like this:
linalg.conv_2d_nhwc  %arg0, %arg1, %arg2 :
  (memref<1x3x3x3xf32>, memref<1x3x3x3xf32>, memref<?x?x?x?xf32>)
This op can be expressed as a dot product between arg0 (input) and arg1 (kernel) which is written into first entry of arg2 (output). This is the ConvOp this pass expects and converts into:
#map0 = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#map1 = affine_map<(d0, d1, d2) -> ()>
.....
%0 = vector.transfer_read %arg0[%c0, %c0, %c0, %c0], %c0_f32
  : memref<1x3x3x3xf32>, vector<3x3x3xf32>
%1 = vector.transfer_read %arg1[%c0, %c0, %c0, %c0], %c0_f32
  : memref<1x3x3x3xf32>, vector<3x3x3xf32>
%2 = vector.contract {indexing_maps = [#map0, #map0, #map1],
  iterator_types = ["reduction", "reduction", "reduction"]} %0, %1,
  %c0_f32 : vector<3x3x3xf32>, vector<3x3x3xf32> into f32
store %2, %arg2[%c0, %c0, %c0, %c0] : memref<?x?x?x?xf32>
where first 2 operations read input and kernel memory buffers into vectors. Subsequently, they are contracted together and the result is written to the first entry of the output buffer.
Definition at line 711 of file Transforms.h.
Constructor & Destructor Documentation
ConvOpVectorization()
template<typename ConvOp, int N> mlir::linalg::ConvOpVectorization< ConvOp, N >::ConvOpVectorization (MLIRContext * context, SmallVector< bool, 4 > msk) inline
Definition at line 716 of file Transforms.h.
References mlir::linalg::applyStagedPatterns().
Member Function Documentation
matchAndRewrite()
template<class ConvOp , int N> LogicalResult ConvOpVectorization::matchAndRewrite (ConvOp minOp, PatternRewriter & rewriter) const override virtual
Reimplemented from mlir::OpRewritePattern< ConvOp >.
Definition at line 372 of file Vectorization.cpp.
References mlir::PatternRewriter::create(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::AffineMap::get(), mlir::VectorType::get(), mlir::getAffineDimExpr(), mlir::Builder::getAffineMapArrayAttr(), mlir::ShapedType::getElementType(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::ShapedType::getRank(), mlir::ShapedType::getShape(), mlir::Builder::getStrArrayAttr(), mlir::Builder::getZeroAttr(), mlir::ShapedType::hasStaticShape(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/Transforms.h
lib/Dialect/Linalg/Transforms/Vectorization.cpp