MLIR: lib/Dialect/Linalg/Utils/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/SCF/EDSC/Builders.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/FoldUtils.h"
Namespaces
mlir
mlir::linalg
Functions
static Value emitOrFoldComposedAffineApply (OpBuilder &b, Location loc, AffineMap map, ValueRange operandsRef, OperationFolder *folder)
static void unpackRanges (ArrayRef< SubViewOp::Range > ranges, SmallVectorImpl< Value > &lbs, SmallVectorImpl< Value > &ubs, SmallVectorImpl< Value > &steps)
Given a list of subview ranges, extract individual values for lower, upper bounds and steps and put them into the corresponding vectors.
SmallVector< Value, 8 > mlir::linalg::getViewSizes (OpBuilder &builder, LinalgOp linalgOp)
Returns the linearized list of all view dimensions in a linalgOp.
Optional< SmallVector< Value, 4 > > mlir::linalg::getLoopRanges (OpBuilder &builder, LinalgOp linalgOp, OperationFolder *folder=nullptr)
Returns the loop ranges of the linalgOp.
static void mlir::linalg::updateBoundsForCyclicDistribution (OpBuilder &builder, Location loc, Value procId, Value nprocs, Value &lb, Value &ub, Value &step)
Update the lb, ub and step to get per processor lb, ub and step.
static void mlir::linalg::generateParallelLoopNest (ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< Attribute > iteratorTypes, function_ref< void(ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > &ivStorage, ArrayRef< DistributionMethod > distributionMethod={})
Generates a loop nest consisting of scf.parallel and scf.for, depending on the `iteratorTypes.
Function Documentation
emitOrFoldComposedAffineApply()
static Value emitOrFoldComposedAffineApply (OpBuilder & b, Location loc, AffineMap map, ValueRange operandsRef, OperationFolder * folder) static
Definition at line 60 of file Utils.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::OperationFolder::create(), and mlir::fullyComposeAffineMapAndOperands().
Referenced by mlir::linalg::applyMapToValues().
unpackRanges()
static void unpackRanges (ArrayRef< SubViewOp::Range > ranges, SmallVectorImpl< Value > & lbs, SmallVectorImpl< Value > & ubs, SmallVectorImpl< Value > & steps) static
Given a list of subview ranges, extract individual values for lower, upper bounds and steps and put them into the corresponding vectors.
Definition at line 136 of file Utils.cpp.
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().