MLIR: lib/Dialect/Linalg/Transforms/FusionOnTensors.cpp File Reference
FusionOnTensors.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LLVM.h"
Functions
static AffineMap linearizeCollapsedDims (AffineMap sourceMap, ArrayRef< int64_t > sourceShape, ArrayRef< AffineMap > reassociationMaps)
Linearize the expressions in sourceMap based on the reassociationMaps provided, given the shape of the source tensor that corresponds to the sourceMap.
static bool isTensorReshapeOpFusible (TensorReshapeOp reshapeOp, AffineMap useIndexMap, bool asProducer)
Checks if the reshapeOp can be fused with it consumer (if asProducer is true) or its producer (if asProducer is false) given the indexing map at its use.
template<typename... Args>
static LinalgOp createLinalgOpOfSameType (LinalgOp op, PatternRewriter &rewriter, Args... args)
Based on the type of op create a linalg op of the same type, i.e.
Function Documentation
createLinalgOpOfSameType()
template<typename... Args> static LinalgOp createLinalgOpOfSameType (LinalgOp op, PatternRewriter & rewriter, Args... args) static
Based on the type of op create a linalg op of the same type, i.e.
if op is a linalg.generic operation, the create a linalg.generic operation with the given args. Expects op to be linalg.generic or linalg.indexed_generic.
Definition at line 337 of file FusionOnTensors.cpp.
References mlir::Region::begin(), mlir::Block::begin(), mlir::Location::cast(), mlir::PatternRewriter::cloneRegionBefore(), mlir::concatAffineMaps(), mlir::PatternRewriter::create(), mlir::OpBuilder::createOrFold(), fuse(), mlir::AffineMapAttr::get(), mlir::RankedTensorType::get(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::Builder::getArrayAttr(), mlir::ShapedType::getElementType(), getElementType(), mlir::Builder::getMultiDimIdentityMap(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Operation::getOperands(), mlir::getParallelIteratorTypeName(), mlir::Operation::getRegion(), mlir::AffineMap::getResults(), mlir::Operation::getResultTypes(), getShape(), mlir::Builder::getUnknownLoc(), mlir::inversePermutation(), isTensorReshapeOpFusible(), linearizeCollapsedDims(), and mlir::BlockAndValueMapping::map().
isTensorReshapeOpFusible()
static bool isTensorReshapeOpFusible (TensorReshapeOp reshapeOp, AffineMap useIndexMap, bool asProducer) static
Checks if the reshapeOp can be fused with it consumer (if asProducer is true) or its producer (if asProducer is false) given the indexing map at its use.
Definition at line 316 of file FusionOnTensors.cpp.
References mlir::AffineMap::isIdentity().
Referenced by createLinalgOpOfSameType().
linearizeCollapsedDims()
static AffineMap linearizeCollapsedDims (AffineMap sourceMap, ArrayRef< int64_t > sourceShape, ArrayRef< AffineMap > reassociationMaps) static
Linearize the expressions in sourceMap based on the reassociationMaps provided, given the shape of the source tensor that corresponds to the sourceMap.
Note that this implicitly assumes that the tensors dimensions are "row-major" ordered logically.
For example:
%0 = op ... : tensor<?x?x4x5xf32> with output index_map affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
and reshape: %1 = linalg.tensor_reshape %0 [affine_map<(i, j, k, l) -> (i)>, affine_map<(i, j, k, l) -> (j, k, l)>] : tensor<?x?x4x5xf32> into tensor<?x?xf32>
would be rewritten into: %0 = op ... : tensor<?x?x4x5xf32> with output index_map affine_map<(d0, d1, d2, d3) -> (d0, d1 * 20 + d2 * 5 + d3)>
Definition at line 288 of file FusionOnTensors.cpp.
References mlir::AffineMap::get(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and mlir::makeCanonicalStridedLayoutExpr().
Referenced by createLinalgOpOfSameType().