MLIR: include/mlir-c/Bindings/Python/Interop.h File Reference
Interop.h File Reference
#include <Python.h>
#include "mlir-c/IR.h"
Macros
#define MLIR_PYTHON_CAPSULE_CONTEXT "mlir.ir.Context._CAPIPtr"
#define MLIR_PYTHON_CAPSULE_MODULE "mlir.ir.Module._CAPIPtr"
#define MLIR_PYTHON_CAPI_PTR_ATTR "_CAPIPtr"
Attribute on MLIR Python objects that expose their C-API pointer.
#define MLIR_PYTHON_CAPI_FACTORY_ATTR "_CAPICreate"
Attribute on MLIR Python objects that exposes a factory function for constructing the corresponding Python object from a type-specific capsule wrapping the C-API pointer.
Functions
PyObject * mlirPythonContextToCapsule (MlirContext context)
Creates a capsule object encapsulating the raw C-API MlirContext.
MlirContext mlirPythonCapsuleToContext (PyObject *capsule)
Extracts a MlirContext from a capsule as produced from mlirPythonContextToCapsule.
PyObject * mlirPythonModuleToCapsule (MlirModule module)
Creates a capsule object encapsulating the raw C-API MlirModule.
Macro Definition Documentation
MLIR_PYTHON_CAPI_FACTORY_ATTR
#define MLIR_PYTHON_CAPI_FACTORY_ATTR "_CAPICreate"
Attribute on MLIR Python objects that exposes a factory function for constructing the corresponding Python object from a type-specific capsule wrapping the C-API pointer.
The signature of the function is: def _CAPICreate(capsule) -> object Calling such a function implies a transfer of ownership of the object the capsule wraps: after such a call, the capsule should be considered invalid, and its wrapped pointer must not be destroyed.
Only a very small number of Python objects can be created in such a fashion (i.e. top-level types such as Context where the lifetime can be cleanly delineated).
Definition at line 53 of file Interop.h.
Referenced by mlir::python::PyType::operator==().
MLIR_PYTHON_CAPI_PTR_ATTR
#define MLIR_PYTHON_CAPI_PTR_ATTR "_CAPIPtr"
Attribute on MLIR Python objects that expose their C-API pointer.
This will be a type-specific capsule created as per one of the helpers below.
Ownership is not transferred by acquiring a capsule in this way: the validity of the pointer wrapped by the capsule will be bounded by the lifetime of the Python object that produced it. Only the name and pointer of the capsule are set. The caller is free to set a destructor and context as needed to manage anything further.
Definition at line 40 of file Interop.h.
Referenced by mlir::python::PyType::operator==().
MLIR_PYTHON_CAPSULE_CONTEXT
#define MLIR_PYTHON_CAPSULE_CONTEXT "mlir.ir.Context._CAPIPtr"
Definition at line 28 of file Interop.h.
Referenced by mlirPythonCapsuleToContext(), and mlirPythonContextToCapsule().
MLIR_PYTHON_CAPSULE_MODULE
#define MLIR_PYTHON_CAPSULE_MODULE "mlir.ir.Module._CAPIPtr"
Definition at line 29 of file Interop.h.
Referenced by mlirPythonModuleToCapsule().
Function Documentation
mlirPythonCapsuleToContext()
MlirContext mlirPythonCapsuleToContext (PyObject * capsule) inline
Extracts a MlirContext from a capsule as produced from mlirPythonContextToCapsule.
If the capsule is not of the right type, then a null context is returned (as checked via mlirContextIsNull). In such a case, the Python APIs will have already set an error.
Definition at line 71 of file Interop.h.
References MLIR_PYTHON_CAPSULE_CONTEXT.
Referenced by mlir::python::PyMlirContext::createFromCapsule().
mlirPythonContextToCapsule()
PyObject* mlirPythonContextToCapsule (MlirContext context) inline
Creates a capsule object encapsulating the raw C-API MlirContext.
The returned capsule does not extend or affect ownership of any Python objects that reference the context in any way.
Definition at line 63 of file Interop.h.
References MLIR_PYTHON_CAPSULE_CONTEXT.
Referenced by mlir::python::PyMlirContext::getCapsule().
mlirPythonModuleToCapsule()
PyObject* mlirPythonModuleToCapsule (MlirModule module) inline
Creates a capsule object encapsulating the raw C-API MlirModule.
The returned capsule does not extend or affect ownership of any Python objects that reference the module in any way.
Definition at line 80 of file Interop.h.
References MLIR_PYTHON_CAPSULE_MODULE.
Referenced by mlir::python::PyModule::getCapsule().