MLIR: lib/Conversion/VectorToSCF/VectorToSCF.cpp File Reference
VectorToSCF.cpp File Reference
#include <type_traits>
#include "mlir/Conversion/VectorToSCF/VectorToSCF.h"
#include "../PassDetail.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SCF/EDSC/Builders.h"
#include "mlir/Dialect/SCF/EDSC/Intrinsics.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Types.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/Passes.h"
Namespaces
mlir
Functions
template<typename TransferOpTy >
static int computeCoalescedIndex (TransferOpTy transfer)
Analyzes the transfer to find an access dimension along the fastest remote MemRef dimension.
static void emitWithBoundsChecks (PatternRewriter &rewriter, VectorTransferOpInterface transfer, ValueRange ivs, const MemRefBoundsCapture &memRefBoundsCapture, function_ref< void(ArrayRef< Value >)> inBoundsFun, function_ref< void(ArrayRef< Value >)> outOfBoundsFun=nullptr)
void mlir::populateVectorToSCFConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *context, const VectorTransferToSCFOptions &options=VectorTransferToSCFOptions())
Collect a set of patterns to convert from the Vector dialect to SCF + std.
Function Documentation
computeCoalescedIndex()
template<typename TransferOpTy > static int computeCoalescedIndex (TransferOpTy transfer) static
Analyzes the transfer to find an access dimension along the fastest remote MemRef dimension.
If such a dimension with coalescing properties is found, pivs and vectorBoundsCapture are swapped so that the invocation of LoopNestBuilder captures it in the innermost loop.
Definition at line 404 of file VectorToSCF.cpp.
References mlir::detail::enumerate(), and mlir::AffineDimExpr::getPosition().
Referenced by mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite().
emitWithBoundsChecks()
static void emitWithBoundsChecks (PatternRewriter & rewriter, VectorTransferOpInterface transfer, ValueRange ivs, const MemRefBoundsCapture & memRefBoundsCapture, function_ref< void(ArrayRef< Value >)> inBoundsFun, function_ref< void(ArrayRef< Value >)> outOfBoundsFun = nullptr) static
Definition at line 446 of file VectorToSCF.cpp.
References mlir::linalg::applyMapToValues(), mlir::edsc::conditionBuilder(), mlir::detail::enumerate(), and mlir::AffineConstantExpr::getValue().
Referenced by mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite().